/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { useState } from "react";
import {
  Menu,
  Layers,
  FileText,
  Download,
  ArrowLeft,
  ArrowRight,
  Home,
  LayoutGrid,
  MessageSquare,
  User,
  X,
  Loader2
} from "lucide-react";
import { jsPDF } from "jspdf";
import { GoogleGenAI } from "@google/genai";

export default function App() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [prompt, setPrompt] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerateAndDownload = async () => {
    if (!prompt.trim()) return;
    setIsGenerating(true);
    try {
      const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
      
      const [textResponse, imgRes1, imgRes2, imgRes3, imgRes4, imgRes5] = await Promise.all([
        ai.models.generateContent({
          model: "gemini-3-flash-preview",
          contents: `Generate a highly detailed, professional architectural dossier for: "${prompt}". The design MUST be strictly eco-friendly, highly sustainable, minimal modern, zero-maintenance, earthquake-resistant, and extreme-weather-resistant. Structure the response with EXACTLY these 5 headings (do not use markdown asterisks, just type the heading in ALL CAPS and a newline): EXECUTIVE SUMMARY, EXTERIOR ARCHITECTURE, INTERIOR SPATIAL LAYOUT, MATERIALITY & RESILIENCE, LIGHTING & ATMOSPHERE. Keep it professional and in-depth (around 800 words).`,
        }),
        ai.models.generateContent({
          model: 'gemini-2.5-flash-image',
          contents: { parts: [{ text: `Hero exterior architectural visualization of: ${prompt}. Eco-friendly, minimal modern design, seamlessly integrated with nature. High quality, photorealistic, wide angle.` }] },
          config: { imageConfig: { aspectRatio: "16:9" } }
        }),
        ai.models.generateContent({
          model: 'gemini-2.5-flash-image',
          contents: { parts: [{ text: `Landscape and site integration of: ${prompt}. Eco-friendly, sustainable architecture, minimal modern design, weather-resistant structure. High quality, photorealistic.` }] },
          config: { imageConfig: { aspectRatio: "16:9" } }
        }),
        ai.models.generateContent({
          model: 'gemini-2.5-flash-image',
          contents: { parts: [{ text: `Interior architectural visualization of: ${prompt}. Eco-friendly, minimal modern design, natural light, raw durable materials. High quality, photorealistic, interior photography.` }] },
          config: { imageConfig: { aspectRatio: "16:9" } }
        }),
        ai.models.generateContent({
          model: 'gemini-2.5-flash-image',
          contents: { parts: [{ text: `Close-up architectural detail shot of: ${prompt}. Showing sustainable, zero-maintenance materials (e.g., green roof, raw concrete, recycled steel). High quality, photorealistic, macro photography.` }] },
          config: { imageConfig: { aspectRatio: "16:9" } }
        }),
        ai.models.generateContent({
          model: 'gemini-2.5-flash-image',
          contents: { parts: [{ text: `Night time architectural visualization of: ${prompt}. Minimal modern design, warm atmospheric lighting, eco-friendly, sustainable. High quality, photorealistic.` }] },
          config: { imageConfig: { aspectRatio: "16:9" } }
        })
      ]);

      const text = textResponse.text || "Plan generated.";
      
      const extractImage = (res) => {
        if (res.candidates?.[0]?.content?.parts) {
          for (const part of res.candidates[0].content.parts) {
            if (part.inlineData) {
              return {
                data: `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`,
                format: part.inlineData.mimeType === 'image/jpeg' ? 'JPEG' : 'PNG'
              };
            }
          }
        }
        return null;
      };

      const img1 = extractImage(imgRes1);
      const img2 = extractImage(imgRes2);
      const img3 = extractImage(imgRes3);
      const img4 = extractImage(imgRes4);
      const img5 = extractImage(imgRes5);

      const doc = new jsPDF();
      const margin = 20;
      const pageWidth = doc.internal.pageSize.getWidth();
      const imgWidth = pageWidth - (margin * 2);
      const textWidth = 130; // Narrower text column for modern editorial look
      
      // COVER PAGE
      doc.setFont("helvetica", "bold");
      doc.setFontSize(28);
      doc.text("ARCHITECTURAL DOSSIER", margin, 40);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      const titleLines = doc.splitTextToSize(`VISION: ${prompt.toUpperCase()}`, imgWidth);
      doc.text(titleLines, margin, 55);
      
      if (img1) {
        doc.addImage(img1.data, img1.format, margin, 75, imgWidth, imgWidth * (9/16));
      }
      
      doc.setFontSize(9);
      doc.text("GENERATED BY AI ARCHITECT", margin, 280);
      
      // CONTENT PAGES
      let currentY = 20;
      doc.addPage();
      
      const lines = text.split('\n').map(l => l.trim()).filter(l => l);
      let sections = [];
      let currentSection = { heading: 'EXECUTIVE SUMMARY', content: [] };
      
      lines.forEach(line => {
        // Identify headings (ALL CAPS, short, no periods at end usually)
        if (line === line.toUpperCase() && line.length < 60 && line.length > 3 && !line.endsWith('.')) {
          if (currentSection.content.length > 0 || currentSection.heading !== 'EXECUTIVE SUMMARY') {
            sections.push(currentSection);
          }
          currentSection = { heading: line, content: [] };
        } else {
          currentSection.content.push(line);
        }
      });
      sections.push(currentSection);
      
      const sectionImages = [null, img2, img3, img4, img5];
      
      sections.forEach((sec, idx) => {
        if (currentY > 220) { doc.addPage(); currentY = 20; }
        
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text(sec.heading, margin, currentY);
        currentY += 12;
        
        const secImg = sectionImages[idx];
        if (secImg) {
          const imgHeight = imgWidth * (9/16);
          if (currentY + imgHeight > 270) {
            doc.addPage(); currentY = 20;
          }
          doc.addImage(secImg.data, secImg.format, margin, currentY, imgWidth, imgHeight);
          currentY += imgHeight + 12;
        }
        
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(60, 60, 60);
        
        sec.content.forEach(p => {
          const splitP = doc.splitTextToSize(p, textWidth);
          if (currentY + (splitP.length * 5) > 280) {
            doc.addPage(); currentY = 20;
          }
          doc.text(splitP, margin, currentY);
          currentY += (splitP.length * 5) + 6;
        });
        
        currentY += 10;
      });
      
      doc.save("minimal-modern-dossier.pdf");

      setIsModalOpen(false);
      setPrompt("");
    } catch (error) {
      console.error(error);
      alert("Failed to generate plan. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };
  return (
    <div className="min-h-screen bg-surface text-on-surface selection:bg-secondary/30 pb-24 md:pb-0">
      {/* TopAppBar */}
      <header className="fixed top-0 left-0 w-full z-50 flex justify-between items-center px-6 h-20 bg-surface/80 backdrop-blur-xl">
        <div className="flex items-center gap-4">
          <button className="text-on-surface hover:text-on-surface-variant transition-colors duration-300">
            <Menu size={24} strokeWidth={1.5} />
          </button>
        </div>
        <div className="text-xl font-serif tracking-[0.2em] uppercase text-on-surface">
          ARCHITECT
        </div>
        <div className="flex items-center">
          <div className="w-8 h-8 bg-surface-container-highest flex items-center justify-center text-[10px] uppercase tracking-widest font-sans text-on-surface">
            PRO
          </div>
        </div>
      </header>

      <main className="pt-20">
        {/* Hero Section */}
        <section className="relative w-full h-[75vh] min-h-[600px] overflow-hidden flex flex-col justify-end p-8 md:p-16">
          <div className="absolute inset-0 z-0">
            <img
              className="w-full h-full object-cover"
              alt="wide shot of a brutalist concrete cafe with large glass windows and minimalist furniture at dusk with warm interior lighting"
              src="https://lh3.googleusercontent.com/aida-public/AB6AXuBY9Bv_YwH-nXn1Mg2eNhjmdGabfW6rSQVx8plyLQzZQYY_9sqt-IHAeVDAl9Rc6IrmmwMOgWGROrDrnRjSPZy76ulNBpEvF9BhYFrdSY0hFzFI7Bpz4y4qN5cV_4ElpD28Sdnk2J_35ETbIg3WufR_Gx0hV4qlHlezJk7Qcx1H0THNqwQk6didcsnrc5KENSkbSeAlrHCqhZhJLpLF5BBNgrtxoNhl3DmYJUQ8EaHmnCWNchBTgQUcmnt4BorE6Ty659ETu9jMRh8"
              referrerPolicy="no-referrer"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-inverse-surface/90 via-inverse-surface/30 to-transparent"></div>
          </div>
          <div className="relative z-10 max-w-5xl">
            <p className="text-[10px] uppercase tracking-[0.3em] text-on-primary mb-4 font-medium">
              Sustainable / Resilient / 2024
            </p>
            <h1 className="text-5xl md:text-7xl font-serif text-on-primary leading-tight mb-8">
              Resilient
              <br />
              Eco-Architecture
            </h1>
            <div className="mt-8 bg-inverse-surface/40 backdrop-blur-md border border-on-primary/20 p-2 flex flex-col md:flex-row gap-2 max-w-2xl">
              <input
                type="text"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="e.g. An off-grid minimal eco-retreat in a dense forest..."
                className="flex-1 bg-transparent text-on-primary placeholder:text-on-primary/60 outline-none px-4 py-2 font-sans text-sm"
                disabled={isGenerating}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && prompt.trim() && !isGenerating) {
                    handleGenerateAndDownload();
                  }
                }}
              />
              <button 
                onClick={handleGenerateAndDownload}
                disabled={!prompt.trim() || isGenerating}
                className="bg-primary text-on-primary px-6 py-3 text-[10px] uppercase tracking-widest font-semibold hover:bg-primary-dim transition-colors flex items-center justify-center gap-2 disabled:opacity-50"
              >
                {isGenerating ? (
                  <><Loader2 size={14} className="animate-spin" /> Drafting 5-Part Dossier...</>
                ) : (
                  <><FileText size={14} /> Generate PDF</>
                )}
              </button>
            </div>
          </div>
        </section>

        {/* Content Grid: Asymmetric Layout */}
        <div className="max-w-7xl mx-auto px-6 mt-24 grid grid-cols-1 md:grid-cols-12 gap-16">
          {/* Project Specs */}
          <aside className="md:col-span-4 space-y-12 order-2 md:order-1">
            <div className="space-y-8">
              <h3 className="text-[10px] uppercase tracking-[0.2em] text-outline font-semibold border-b border-outline-variant/20 pb-2">
                Project Specs
              </h3>
              <div className="grid grid-cols-2 gap-y-8 gap-x-4">
                <div>
                  <p className="text-[9px] uppercase tracking-widest text-on-surface-variant mb-1">
                    Area
                  </p>
                  <p className="text-xl font-serif text-on-surface">450 m²</p>
                </div>
                <div>
                  <p className="text-[9px] uppercase tracking-widest text-on-surface-variant mb-1">
                    Location
                  </p>
                  <p className="text-xl font-serif text-on-surface">
                    Oslo, Norway
                  </p>
                </div>
                <div>
                  <p className="text-[9px] uppercase tracking-widest text-on-surface-variant mb-1">
                    Materials
                  </p>
                  <p className="text-sm font-sans leading-relaxed text-on-surface">
                    Cross-Laminated Timber, Recycled Steel, Rammed Earth
                  </p>
                </div>
                <div>
                  <p className="text-[9px] uppercase tracking-widest text-on-surface-variant mb-1">
                    Resilience
                  </p>
                  <p className="text-xl font-serif text-on-surface">
                    Seismic Base Isolation
                  </p>
                </div>
              </div>
            </div>
            <div className="bg-surface-container-low p-8 space-y-4">
              <p className="text-[10px] uppercase tracking-widest text-secondary font-bold">
                The Blueprint
              </p>
              <p className="text-sm text-on-surface-variant leading-relaxed">
                A study in sustainable endurance. Exploring the intersection of minimal modernism with zero-maintenance, weather-resistant, and earthquake-proof engineering.
              </p>
              <div className="pt-4 flex items-center gap-4 text-outline font-mono text-[10px]">
                <span>01</span>
                <div className="h-[1px] flex-1 bg-outline-variant/30"></div>
                <span>100</span>
              </div>
            </div>
          </aside>

          {/* Designer Notes */}
          <section className="md:col-span-8 order-1 md:order-2">
            <div className="max-w-2xl">
              <h2 className="text-3xl font-serif mb-8 text-on-surface">
                Designer Notes
              </h2>
              <div className="space-y-6 text-on-surface-variant leading-relaxed text-lg font-light">
                <p>
                  Our architecture is born from a desire to strip away the artifice of traditional construction while fortifying against the unpredictable. We approach every site with a minimal modern ethos, carving out volumes that invite natural light while utilizing zero-maintenance, hyper-durable materials.
                </p>
                <p>
                  Every seam in the structure is engineered for extreme weather resistance and seismic stability. The silence of the space is its primary luxury, providing a sustainable, eco-friendly sanctuary that stands unyielding against the elements.
                </p>
              </div>
            </div>

            <div className="mt-16 border-t border-outline-variant/20 pt-12">
              <h3 className="text-[10px] uppercase tracking-[0.2em] text-outline font-semibold mb-6">
                Architectural Assets
              </h3>
              <div className="grid grid-cols-1 gap-6">
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
                  <div className="max-w-md">
                    <p className="text-sm text-on-surface-variant leading-relaxed">
                      Includes detailed floor plans, structural sections, and
                      material schedules ready for construction.
                    </p>
                  </div>
                  <button 
                    onClick={() => setIsModalOpen(true)}
                    className="flex items-center gap-4 bg-surface-container-high hover:bg-surface-container-highest transition-colors px-6 py-4 border border-outline-variant/20 group w-full md:w-auto text-left"
                  >
                    <div className="w-12 h-12 flex items-center justify-center bg-primary text-on-primary shrink-0">
                      <FileText size={20} strokeWidth={1.5} />
                    </div>
                    <div className="text-left flex-1">
                      <div className="text-[10px] uppercase tracking-widest font-bold text-on-surface">
                        Generate & Download Plan
                      </div>
                      <div className="text-[9px] uppercase tracking-widest text-on-surface-variant mt-0.5">
                        AI-Generated PDF
                      </div>
                    </div>
                    <Download
                      size={20}
                      strokeWidth={1.5}
                      className="ml-4 text-outline group-hover:text-primary transition-colors shrink-0"
                    />
                  </button>
                </div>
              </div>
            </div>

            {/* Gallery: Bento Grid inspired */}
            <div className="mt-20 grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="aspect-square bg-surface-container overflow-hidden">
                <img
                  className="w-full h-full object-cover grayscale hover:grayscale-0 transition-all duration-700"
                  alt="detail shot of raw concrete wall texture with sharp shadows and a single minimalist wooden bench"
                  src="https://lh3.googleusercontent.com/aida-public/AB6AXuBaQqvOnhJiL1JezzZ1YxGRbRaUgLTJf8zwocV0EK4V8wz6wf1M_8eXDF5Rd5LAnfbxmvz4BEU0bZgEaBS6Mted5TwTB31gp6CLdQqfTLNU1OhJ38mAJF2eLTCaJo7rbPbHIA_UJ50o8bcVF6UEz5vdgP0qVT_hxs6lUSrgxl2LN0aKZeKNnMo61XSu7xR3e5JOBn1rcVawaMn_BBfr0-Vtlf6cIGlMXac-JQMuisNKVCCHzd3YDUDjLL0SmG_NZ2Ya7DoESy7l0aQ"
                  referrerPolicy="no-referrer"
                />
              </div>
              <div className="aspect-[3/4] bg-surface-container overflow-hidden md:mt-12">
                <img
                  className="w-full h-full object-cover grayscale hover:grayscale-0 transition-all duration-700"
                  alt="interior view of an office space with floor-to-ceiling windows and clean architectural lines"
                  src="https://lh3.googleusercontent.com/aida-public/AB6AXuCtGvBn9abVhp7MyQoK4sHoe_vgH6yHkcfhGKDCQTI3CZDaFRY4I3bOutmsKKy9VyDI871myVhRLFFza5UNVF90in8WYJcaaPYYsu4ko-VDLjHaN-apK_vgXEhZuB2hv0pK0YPz-f31el3ocfaew4Xe2K59f7hfmyMqQ2Q9pM2eK_TzMjWWdUv9fEmH6p6EXCmHeDCwk1EWPdv8g5VvvVih-e9Bjc_hvZPwPQrRYjv3BZuJtkwfwOvvcvikEBue_MFqsVzM_V2n7rY"
                  referrerPolicy="no-referrer"
                />
              </div>
              <div className="md:col-span-2 aspect-[16/9] bg-surface-container overflow-hidden mt-4">
                <img
                  className="w-full h-full object-cover grayscale hover:grayscale-0 transition-all duration-700"
                  alt="close-up architectural detail of steel and glass intersection on a modern building facade"
                  src="https://lh3.googleusercontent.com/aida-public/AB6AXuBRgdqc6yePizYp3GlM9knuctKONm00jLNS4FeaX6yO0o_wVPjuLm5r3YB_p3SvKVPYRblUgLv6Q7FPi-INpficrQDlfbLqUnia_Ni83CtOfeUxAGuc9FpgJtlEp6HORmbO77tYwyMtKWi044nYQ3kOOjzQUtV6eW7ONv8sB3L5fY602536KTpcTVELh2342eBF531C07eA7qOkBU8DFooWfrNj_G8NvWsPrOz3wVqaA65Pp1HVlc7pAvRopzxPz0O5sbuURIclDMY"
                  referrerPolicy="no-referrer"
                />
              </div>
            </div>
          </section>
        </div>

        {/* Next Project Preview */}
        <section className="mt-32 border-t border-outline-variant/20 pt-20 pb-32 px-6">
          <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-end gap-8">
            <div>
              <p className="text-[10px] uppercase tracking-widest text-outline mb-4 font-semibold">
                Up Next
              </p>
              <h2 className="text-4xl md:text-6xl font-serif text-on-surface opacity-40 hover:opacity-100 transition-opacity cursor-pointer">
                Nordic Glass Pavillion
              </h2>
            </div>
            <div className="flex gap-4">
              <button className="w-12 h-12 flex items-center justify-center border border-outline-variant/30 hover:border-on-surface transition-colors text-on-surface">
                <ArrowLeft size={20} strokeWidth={1.5} />
              </button>
              <button className="w-12 h-12 flex items-center justify-center border border-outline-variant/30 hover:border-on-surface transition-colors text-on-surface">
                <ArrowRight size={20} strokeWidth={1.5} />
              </button>
            </div>
          </div>
        </section>
      </main>

      {/* BottomNavBar (Mobile/Tablet) */}
      <nav className="md:hidden fixed bottom-0 left-0 w-full z-50 flex justify-around items-center px-4 pb-6 pt-4 bg-surface/90 backdrop-blur-md border-t border-outline-variant/20">
        <a
          href="#"
          className="flex flex-col items-center justify-center text-outline hover:text-on-surface transition-colors"
        >
          <Home size={20} strokeWidth={1.5} />
          <span className="text-[9px] font-medium tracking-widest uppercase mt-1.5">
            Home
          </span>
        </a>
        <a
          href="#"
          className="flex flex-col items-center justify-center text-on-surface border-t-2 border-on-surface pt-0 -mt-4"
        >
          <div className="pt-4 flex flex-col items-center">
            <LayoutGrid size={20} strokeWidth={2} />
            <span className="text-[9px] font-bold tracking-widest uppercase mt-1.5">
              Explore
            </span>
          </div>
        </a>
        <a
          href="#"
          className="flex flex-col items-center justify-center text-outline hover:text-on-surface transition-colors"
        >
          <Layers size={20} strokeWidth={1.5} />
          <span className="text-[9px] font-medium tracking-widest uppercase mt-1.5">
            Moodboard
          </span>
        </a>
        <a
          href="#"
          className="flex flex-col items-center justify-center text-outline hover:text-on-surface transition-colors"
        >
          <MessageSquare size={20} strokeWidth={1.5} />
          <span className="text-[9px] font-medium tracking-widest uppercase mt-1.5">
            Inquiry
          </span>
        </a>
        <a
          href="#"
          className="flex flex-col items-center justify-center text-outline hover:text-on-surface transition-colors"
        >
          <User size={20} strokeWidth={1.5} />
          <span className="text-[9px] font-medium tracking-widest uppercase mt-1.5">
            Profile
          </span>
        </a>
      </nav>

      {/* Generation Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-inverse-surface/80 backdrop-blur-sm p-4">
          <div className="bg-surface w-full max-w-lg p-8 shadow-2xl relative border border-outline-variant/20">
            <button 
              onClick={() => !isGenerating && setIsModalOpen(false)}
              className="absolute top-6 right-6 text-outline hover:text-on-surface transition-colors"
              disabled={isGenerating}
            >
              <X size={24} strokeWidth={1.5} />
            </button>
            
            <h3 className="text-2xl font-serif text-on-surface mb-2">
              Design Your Plan
            </h3>
            <p className="text-sm text-on-surface-variant mb-6 font-light">
              Describe your vision. Our AI architect will draft a multi-page professional dossier including exterior, interior, and detail renderings for you to download as a PDF.
            </p>
            
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g. An off-grid minimal eco-retreat in a dense forest, focusing on natural light and zero-maintenance..."
              className="w-full bg-surface-container-low border-b border-outline focus:border-secondary outline-none p-4 text-sm font-sans resize-none h-32 transition-colors text-on-surface placeholder:text-outline-variant"
              disabled={isGenerating}
            />
            
            <button 
              onClick={handleGenerateAndDownload}
              disabled={!prompt.trim() || isGenerating}
              className="bg-primary text-on-primary px-8 py-4 text-[10px] uppercase tracking-widest font-semibold hover:bg-primary-dim transition-colors w-full mt-6 flex justify-center items-center gap-3 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isGenerating ? (
                <>
                  <Loader2 size={16} className="animate-spin" />
                  Drafting 5-Part Dossier & Renderings...
                </>
              ) : (
                <>
                  <FileText size={16} />
                  Generate PDF
                </>
              )}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
